import { AIPlugin, AICapability } from '../../core/types';

export class CompanyAIPlugin implements AIPlugin {
  public id = 'company_plugin';
  public name = 'Company AI Plugin';

  public register(registry: any): void {
    // Register capabilities
    
    const seoAuditCapability: AICapability = {
      id: 'COMPANY_SEO_AUDIT',
      name: 'SEO Audit',
      description: 'Generates SEO tags and content for a Company',
      policyId: 'DEFAULT_POLICY',
      activeVersion: 1,
      promptVersions: [
        {
          version: 1,
          systemPrompt: 'You are an expert SEO auditor. Analyze the provided company data and output an SEO meta JSON.',
          userTemplate: 'Analyze this context: {{context}}',
          outputSchema: {
            type: 'object',
            properties: {
              metaTitle: { type: 'string' },
              metaDescription: { type: 'string' },
              keywords: { type: 'string' } // comma separated
            }
          },
          temperature: 0.2,
          tags: ['seo', 'company']
        }
      ],
      mapper: (output: any, context: any) => {
        // Generates AISuggestions based on operation types
        return [
          {
            targetField: 'profile.metaTitle',
            operation: 'REPLACE',
            payload: { newValue: output.metaTitle },
            reason: 'Generated by AI based on company profile'
          },
          {
            targetField: 'profile.metaDescription',
            operation: 'REPLACE',
            payload: { newValue: output.metaDescription },
            reason: 'Generated by AI based on company profile'
          }
        ];
      }
    };

    registry.capabilities.register(seoAuditCapability);
    
    // In the future, register ProfileWriter, PortfolioWriter etc.
  }
}
