const fs = require('fs');
const content = fs.readFileSync('src/pages/Workspace.jsx.orig', 'utf8');
const rkkStartToken = "{subTab === 'rkk' && (";
const scheduleStartToken = "{subTab === 'schedule' && (";
let rkkStartIdx = content.indexOf(rkkStartToken);
let scheduleStartIdx = content.indexOf(scheduleStartToken);
let rkkBlock = content.substring(rkkStartIdx, scheduleStartIdx);
let rkkInnerStart = rkkBlock.indexOf('<div className="flex flex-col h-full bg-slate-50">');
let rkkInnerEnd = rkkBlock.lastIndexOf(')}');
let rkkInner = rkkBlock.substring(rkkInnerStart, rkkInnerEnd).trim();
console.log("RKK INNER ENDS WITH:", rkkInner.slice(-50));
