export const EventNames = {
  WORKSPACE_CREATED: 'workspace.created',
  WORKSPACE_UPDATED: 'workspace.updated',
  WORKSPACE_DELETED: 'workspace.deleted',
  WORKSPACE_RESTORED: 'workspace.restored',
  COMPANY_CREATED: 'company.created',
  COMPANY_UPDATED: 'company.updated',
  COMPANY_DELETED: 'company.deleted',
  COMPANY_RESTORED: 'company.restored',
  SUPPLIER_CREATED: 'supplier.created',
  SUPPLIER_UPDATED: 'supplier.updated',
  SUPPLIER_DELETED: 'supplier.deleted',
  SUPPLIER_RESTORED: 'supplier.restored',
  DOCUMENT_UPLOADED: 'document.uploaded',
  DOCUMENT_HASHED: 'document.hashed',
  DOCUMENT_SCANNED: 'document.scanned',
  DOCUMENT_DUPLICATE_FOUND: 'document.duplicate_found',
  DOCUMENT_EXTRACTION_COMPLETED: 'document.extraction_completed',
  DOCUMENT_EMBEDDING_CREATED: 'document.embedding_created',
  VALIDATION_COMPLETED: 'validation.completed',
  EQUIPMENT_CREATED: 'equipment.created',
  EQUIPMENT_UPDATED: 'equipment.updated',
  EQUIPMENT_ASSIGNED: 'equipment.assigned',
  EQUIPMENT_RELEASED: 'equipment.released',
  CERTIFICATION_UPDATED: 'certification.updated',
  CERTIFICATION_EXPIRED: 'certification.expired',
  MAINTENANCE_SCHEDULED: 'maintenance.scheduled',
  MAINTENANCE_COMPLETED: 'maintenance.completed',
  FEATURE_VECTOR_UPDATED: 'feature_vector.updated',
  EQUIPMENT_CERTIFICATION_VERIFIED: 'equipment.certification_verified',
  EQUIPMENT_REPLACEMENT_RISK_UPDATED: 'equipment.replacement_risk_updated',
  TENDER_CREATED: 'tender.created',
  TENDER_PUBLISHED: 'tender.published',
  TENDER_SUPPLIER_INVITED: 'tender.supplier_invited',
  TENDER_BID_SUBMITTED: 'tender.bid_submitted',
  TENDER_EVALUATION_STARTED: 'tender.evaluation_started',
  TENDER_AWARDED: 'tender.awarded',
  TENDER_REQUIREMENT_UPDATED: 'tender.requirement_updated',
  TENDER_DOCUMENT_ADDED: 'tender.document_added',
  TENDER_SUPPLIER_SHORTLISTED: 'tender.supplier_shortlisted',
  TENDER_NEGOTIATION_STARTED: 'tender.negotiation_started',
  TENDER_COMPLETED: 'tender.completed',
} as const;

export type EventName = typeof EventNames[keyof typeof EventNames];
